### ISSUE TITLE
Slack tab missing

### ISSUE THREAD

**Issue by skion** [PeteGoo/tcSlackBuildNotifier#138]
In TC 2017.1 I seem to see the see the "Slack Notifications" tab in the Administration section, but no Slack tab in any of the Projects or Build Configurations.

Could this be due to missing support for TeamCity 2017.1?

**Comment by stevenmah** [comment]
Also can't seem to find the tab for 10.0.4 either

**Comment by danieljimenez** [comment]
FWIW it's working for me in 2017.1. I see the tab on all projects but root.

**Comment by PeteGoo** [comment]
@skion can you confirm if you can see it on non root projects?

**Comment by nmb88** [comment]
I believe I may have figured out @skion's issue.  I also didn't see the Slack tab on build configurations or projects (root or otherwise), but the "Slack Notifications" _is_ in the Administration screen.  I'm on TeamCity 10.0.0.  I thought I may be looking in the wrong place:

![image](https://user-images.githubusercontent.com/17556044/26837157-ef897bca-4a99-11e7-9ba1-264c2487968c.png)

Turns out I was.  I can see it on the Project Home screen for Projects/Build Configurations.  From there it can be configured.  

![image](https://user-images.githubusercontent.com/17556044/26837456-aea12350-4a9a-11e7-8bd1-2e4092f32901.png)

Perhaps adding more specific instructions and/or screenshots may be the resolution to this issue?

**Comment by skion** [comment]
Very strange, I should have made some screenshots, it seems to work fine now. Could it be that the Slack tab only appears after configuring Slack in the Administration panel?
