### ISSUE TITLE
Project-specific slacks

### ISSUE THREAD

**Issue by l3m** [PeteGoo/tcSlackBuildNotifier#57]
We have multiple teams that use different slacks, but they all build on the same TeamCity server (different projects though). 

There does not seem to be a way to use different teams per server - as far as I understand, this plugin can post only to a single team. 

This should be a setting that is configurable per-project.

**Comment by shaneedwards** [comment]
Same issue here--we have multiple teams all using TeamCity and all have their own Slack team for separation.  We really need to be able to put the full Slack URL in notification setup rather than just the channel name.  If we could do that and supply the API key then we would have ultimate flexibility.

**Comment by PeteGoo** [comment]
I am currently working on this when I find time

**Comment by gzhytar** [comment]
+1 to this request. 

P.S. Pete, Ive installed latest build in our production and it runs very smoothly. Kudos to you and other contributors who made this one happen and keep working on it. Good job, folks!

**Comment by AliakseiT** [comment]
+1. Thanks for your work, Pete.

**Comment by surg** [comment]
+1 for this feature :) Would be great to be able to specify the webhook url per notification

**Comment by PeteGoo** [comment]
Contributed by @surg and released in 1.4.3
https://github.com/PeteGoo/tcSlackBuildNotifier/releases/tag/1.4.3

**Comment by l3m** [comment]
Amazing! Thanks a lot, @PeteGoo and @surg.
